apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: allow-proxy-to-frontend
    namespace: backtrade
spec:
    podSelector:
        matchLabels:
            app: frontend
            component: web
    policyTypes:
        - Ingress
    ingress:
        - from:
              - podSelector:
                    matchLabels:
                        app: proxy
                        component: nginx
          ports:
              - protocol: TCP
                port: 80
